[[headers]]
  for = "/rss.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  package = "netlify-plugin-cypress"

[build]
  command = "npm run netlify"
  functions = "public/functions/"
